import type { ServiceItem } from "./types";

const img = {
  phuket: "/images/dg-phuket.jpg",
  krabi: "/images/dg-krabi.jpg",
  samui: "/images/dg-samui.jpg",
  trang: "/images/dg-trang.jpg",
  songkhla: "/images/dg-songkhla.jpg",
};

export const SERVICES: ServiceItem[] = [
  {
    id: "1",
    slug: "phuket-3d2n-package",
    title: "แพ็กเกจทัวร์ภูเก็ต 3 วัน 2 คืน",
    category: "tour",
    subcategory: "แพ็กเกจทัวร์ในประเทศ",
    destination: ["phuket"],
    image: img.phuket,
    description:
      "ทริปทะเลใต้ครบวงจร รวมที่พัก เรือสปีดโบ๊ท และกิจกรรมน้ำ เหมาะกับครอบครัวและคู่รัก",
    rating: 4.9,
    reviewCount: 186,
    price: 8900,
    priceUnit: "บาท / คน",
    duration: "3d2n",
    travelType: ["family", "couple", "group"],
    features: ["รวมที่พัก", "รวมอาหารเช้า", "ปรับโปรแกรมได้"],
    badges: ["แนะนำ", "ยอดนิยม"],
    isFeatured: true,
    isFavorite: false,
    createdAt: "2026-03-01",
  },
  {
    id: "2",
    slug: "private-airport-transfer",
    title: "บริการรถรับส่งสนามบินแบบส่วนตัว",
    category: "transfer",
    subcategory: "รถรับส่งสนามบิน",
    destination: ["bangkok", "phuket", "chiangmai"],
    image: img.samui,
    description:
      "รถส่วนตัวพร้อมคนขับ รับ-ส่งสนามบินไปโรงแรม รองรับเที่ยวบินล่าช้าและปรับเวลาได้",
    rating: 4.8,
    reviewCount: 312,
    price: 900,
    priceUnit: "บาท / เที่ยว",
    duration: "halfday",
    travelType: ["private", "vip", "family"],
    features: ["พร้อมคนขับ", "ยืนยันทันที", "รองรับเที่ยวบินล่าช้า"],
    badges: ["แนะนำ"],
    isFeatured: true,
    isFavorite: false,
    createdAt: "2026-02-12",
  },
  {
    id: "3",
    slug: "corporate-mice-incentive",
    title: "Corporate Meeting & Incentive",
    category: "mice",
    subcategory: "Incentive Travel",
    destination: ["bangkok", "phuket", "pattaya"],
    image: img.trang,
    description:
      "วางแผนประชุม สัมมนา Team Building และทริปองค์กรครบวงจร พร้อมสถานที่และโลจิสติกส์",
    rating: 4.9,
    reviewCount: 94,
    price: null,
    priceUnit: "ขอใบเสนอราคา",
    duration: "custom",
    travelType: ["corporate", "group"],
    features: ["รองรับกรุ๊ปองค์กร", "ปรับแต่งโปรแกรมได้", "พร้อมไกด์"],
    badges: ["แนะนำ", "ปรับโปรแกรมได้"],
    isFeatured: true,
    isFavorite: false,
    createdAt: "2026-01-20",
  },
  {
    id: "4",
    slug: "luxury-resort-thailand",
    title: "โรงแรมและรีสอร์ตหรูในประเทศไทย",
    category: "hotel",
    subcategory: "Luxury Hotel",
    destination: ["phuket", "samui", "krabi", "huahin"],
    image: img.krabi,
    description:
      "คัดสรรโรงแรมและรีสอร์ตระดับพรีเมียม พร้อมเรทพิเศษและห้องพักสำหรับกรุ๊ป",
    rating: 4.7,
    reviewCount: 128,
    price: 3500,
    priceUnit: "บาท / คืน",
    duration: "custom",
    travelType: ["vip", "couple", "family"],
    features: ["รวมที่พัก", "ปรับแต่งโปรแกรมได้"],
    badges: ["ยอดนิยม"],
    isFeatured: false,
    isFavorite: false,
    createdAt: "2025-12-08",
  },
  {
    id: "5",
    slug: "boutique-hotel-bangkok",
    title: "Boutique Hotel กรุงเทพฯ",
    category: "hotel",
    subcategory: "Boutique Hotel",
    destination: ["bangkok"],
    image: img.songkhla,
    description:
      "โรงแรมบูทีคใจกลางเมือง บรรยากาศอบอุ่น เหมาะกับทริปสั้นและนักธุรกิจ",
    rating: 4.6,
    reviewCount: 76,
    price: 2800,
    priceUnit: "บาท / คืน",
    duration: "1day",
    travelType: ["private", "couple", "corporate"],
    features: ["รวมที่พัก"],
    badges: [],
    isFeatured: false,
    isFavorite: false,
    createdAt: "2025-11-15",
  },
  {
    id: "6",
    slug: "private-pool-villa",
    title: "Villa และ Private Pool Villa",
    category: "hotel",
    subcategory: "Villa และ Private Pool Villa",
    destination: ["phuket", "samui", "krabi"],
    image: img.phuket,
    description:
      "วิลล่าส่วนตัวพร้อมสระว่ายน้ำ ส่วนตัวสูง เหมาะกับครอบครัวและกลุ่มเพื่อน",
    rating: 4.9,
    reviewCount: 54,
    price: 12000,
    priceUnit: "บาท / คืน",
    duration: "custom",
    travelType: ["family", "vip", "private"],
    features: ["รวมที่พัก", "ปรับแต่งโปรแกรมได้"],
    badges: ["แนะนำ"],
    isFeatured: true,
    isFavorite: false,
    createdAt: "2026-02-01",
  },
  {
    id: "7",
    slug: "domestic-group-tour",
    title: "ทัวร์กรุ๊ปในประเทศ",
    category: "tour",
    subcategory: "ทัวร์กรุ๊ป",
    destination: ["chiangmai", "chiangrai", "pattaya"],
    image: img.trang,
    description:
      "ทัวร์หมู่คณะพร้อมไกด์และรถบัส โปรแกรมชัดเจน ดูแลตั้งแต่ต้นทางถึงปลายทาง",
    rating: 4.5,
    reviewCount: 210,
    price: 4500,
    priceUnit: "บาท / คน",
    duration: "3d2n",
    travelType: ["group", "student", "family"],
    features: ["พร้อมไกด์", "รวมอาหาร", "รวมที่พัก"],
    badges: ["ยอดนิยม"],
    isFeatured: false,
    isFavorite: false,
    createdAt: "2025-10-22",
  },
  {
    id: "8",
    slug: "honeymoon-package",
    title: "ทัวร์คู่รักและฮันนีมูน",
    category: "tour",
    subcategory: "ทัวร์คู่รักและฮันนีมูน",
    destination: ["samui", "phuket", "krabi"],
    image: img.samui,
    description:
      "โปรแกรมโรแมนติกส่วนตัว ห้องพักวิวทะเล ดินเนอร์พิเศษ และกิจกรรมคู่",
    rating: 4.9,
    reviewCount: 67,
    price: 15900,
    priceUnit: "บาท / คู่",
    duration: "4plus",
    travelType: ["couple", "vip", "private"],
    features: ["รวมที่พัก", "รวมอาหาร", "ปรับแต่งโปรแกรมได้"],
    badges: ["แนะนำ"],
    isFeatured: false,
    isFavorite: false,
    createdAt: "2026-01-05",
  },
  {
    id: "9",
    slug: "luxury-travel-package",
    title: "Luxury Travel Package",
    category: "tour",
    subcategory: "Luxury Travel Package",
    destination: ["phuket", "international"],
    image: img.krabi,
    description:
      "แพ็กเกจหรูระดับพรีเมียม ที่พัก 5 ดาว รถส่วนตัว และประสบการณ์พิเศษ",
    rating: 5.0,
    reviewCount: 41,
    price: 45000,
    priceUnit: "บาท / คน",
    duration: "4plus",
    travelType: ["vip", "private", "couple"],
    features: ["พร้อมคนขับ", "พร้อมไกด์", "รวมที่พัก"],
    badges: ["แนะนำ"],
    isFeatured: false,
    isFavorite: false,
    createdAt: "2025-09-18",
  },
  {
    id: "10",
    slug: "private-fit-itinerary",
    title: "โปรแกรมเดินทางแบบส่วนตัว (FIT)",
    category: "fit",
    subcategory: "โปรแกรมเดินทางแบบส่วนตัว",
    destination: ["bangkok", "chiangmai", "phuket"],
    image: img.songkhla,
    description:
      "ออกแบบเส้นทางตามความต้องการ พร้อมไกด์และรถส่วนตัวตลอดทริป",
    rating: 4.8,
    reviewCount: 112,
    price: 6500,
    priceUnit: "บาท / คน / วัน",
    duration: "custom",
    travelType: ["private", "family", "vip"],
    features: ["พร้อมไกด์", "พร้อมคนขับ", "ปรับแต่งโปรแกรมได้"],
    badges: ["ปรับโปรแกรมได้"],
    isFeatured: false,
    isFavorite: false,
    createdAt: "2026-02-28",
  },
  {
    id: "11",
    slug: "luxury-fit",
    title: "Luxury FIT",
    category: "fit",
    subcategory: "Luxury FIT",
    destination: ["phuket", "samui", "krabi"],
    image: img.phuket,
    description:
      "ทัวร์ส่วนตัวระดับลักชัวรี เน้นความเป็นส่วนตัวและความสะดวกสูงสุด",
    rating: 4.9,
    reviewCount: 38,
    price: 18000,
    priceUnit: "บาท / คน / วัน",
    duration: "custom",
    travelType: ["vip", "private", "couple"],
    features: ["พร้อมไกด์", "พร้อมคนขับ", "รวมอาหาร"],
    badges: ["แนะนำ"],
    isFeatured: false,
    isFavorite: false,
    createdAt: "2025-12-30",
  },
  {
    id: "12",
    slug: "special-interest-tour",
    title: "Special Interest Tour",
    category: "fit",
    subcategory: "Special Interest Tour",
    destination: ["chiangmai", "chiangrai", "international"],
    image: img.trang,
    description:
      "ทัวร์ตามความสนใจพิเศษ เช่น กอล์ฟ สปา วัฒนธรรม หรือถ่ายภาพ",
    rating: 4.7,
    reviewCount: 29,
    price: 9800,
    priceUnit: "บาท / คน",
    duration: "3d2n",
    travelType: ["private", "couple", "corporate"],
    features: ["ปรับแต่งโปรแกรมได้", "พร้อมไกด์"],
    badges: [],
    isFeatured: false,
    isFavorite: false,
    createdAt: "2025-08-14",
  },
  {
    id: "13",
    slug: "team-building-outing",
    title: "Team Building & Company Outing",
    category: "mice",
    subcategory: "Team Building",
    destination: ["pattaya", "huahin", "khaolak"],
    image: img.samui,
    description:
      "กิจกรรมทีมและทริปองค์กรที่สนุกและมีสาระ พร้อมสถานที่และอุปกรณ์ครบ",
    rating: 4.8,
    reviewCount: 83,
    price: null,
    priceUnit: "ขอใบเสนอราคา",
    duration: "2d1n",
    travelType: ["corporate", "group"],
    features: ["รองรับกรุ๊ปองค์กร", "ปรับแต่งโปรแกรมได้"],
    badges: ["ยอดนิยม"],
    isFeatured: false,
    isFavorite: false,
    createdAt: "2026-01-12",
  },
  {
    id: "14",
    slug: "destination-wedding",
    title: "Destination Wedding",
    category: "mice",
    subcategory: "Destination Wedding",
    destination: ["phuket", "samui", "krabi"],
    image: img.krabi,
    description:
      "จัดงานแต่งงานริมทะเล พร้อมประสานแขก ที่พัก และพิธีการแบบครบวงจร",
    rating: 5.0,
    reviewCount: 22,
    price: null,
    priceUnit: "ขอใบเสนอราคา",
    duration: "custom",
    travelType: ["couple", "vip", "family"],
    features: ["ปรับแต่งโปรแกรมได้", "รวมที่พัก"],
    badges: ["แนะนำ"],
    isFeatured: false,
    isFavorite: false,
    createdAt: "2025-07-09",
  },
  {
    id: "15",
    slug: "suvanabhumi-private-transfer",
    title: "รถรับส่งสนามบินสุวรรณภูมิแบบส่วนตัว",
    category: "transfer",
    subcategory: "รถรับส่งสนามบิน",
    destination: ["bangkok"],
    image: img.songkhla,
    description:
      "รถส่วนตัวพร้อมคนขับ รองรับการเดินทางจากสุวรรณภูมิไปโรงแรมและสถานที่ต่าง ๆ",
    rating: 4.8,
    reviewCount: 245,
    price: 900,
    priceUnit: "บาท / เที่ยว",
    duration: "halfday",
    travelType: ["private", "family", "vip"],
    features: ["พร้อมคนขับ", "ยืนยันการจองทันที", "รองรับเที่ยวบินล่าช้า"],
    badges: ["ยอดนิยม"],
    isFeatured: false,
    isFavorite: false,
    createdAt: "2026-03-10",
  },
  {
    id: "16",
    slug: "vip-limousine",
    title: "รถลีมูซีนและ Private Transfer",
    category: "transfer",
    subcategory: "รถลีมูซีน",
    destination: ["bangkok", "phuket"],
    image: img.phuket,
    description:
      "บริการรถลีมูซีนระดับพรีเมียม สำหรับแขก VIP และผู้บริหาร",
    rating: 4.9,
    reviewCount: 61,
    price: 4500,
    priceUnit: "บาท / เที่ยว",
    duration: "halfday",
    travelType: ["vip", "corporate", "private"],
    features: ["พร้อมคนขับ"],
    badges: ["แนะนำ"],
    isFeatured: false,
    isFavorite: false,
    createdAt: "2025-11-02",
  },
  {
    id: "17",
    slug: "group-bus-charter",
    title: "รถบัสสำหรับกรุ๊ปและอีเวนต์",
    category: "transfer",
    subcategory: "รถบัสสำหรับกรุ๊ป",
    destination: ["bangkok", "pattaya", "huahin"],
    image: img.trang,
    description:
      "เช่ารถบัสพร้อมคนขับสำหรับกรุ๊ปทัวร์ ประชุม และงานอีเวนต์",
    rating: 4.6,
    reviewCount: 97,
    price: 8500,
    priceUnit: "บาท / วัน",
    duration: "1day",
    travelType: ["group", "corporate", "student"],
    features: ["พร้อมคนขับ", "รองรับกรุ๊ปองค์กร"],
    badges: [],
    isFeatured: false,
    isFavorite: false,
    createdAt: "2025-09-01",
  },
  {
    id: "18",
    slug: "domestic-flight-ticket",
    title: "ตั๋วเครื่องบินในประเทศและต่างประเทศ",
    category: "ticket",
    subcategory: "ตั๋วเครื่องบิน",
    destination: ["bangkok", "phuket", "chiangmai", "international"],
    image: img.samui,
    description:
      "จองตั๋วเครื่องบินพร้อมคำปรึกษาเส้นทางและตารางบินที่เหมาะสม",
    rating: 4.5,
    reviewCount: 154,
    price: 1200,
    priceUnit: "บาท / คน",
    duration: "custom",
    travelType: ["private", "family", "group", "corporate"],
    features: ["ปรับแต่งโปรแกรมได้"],
    badges: [],
    isFeatured: false,
    isFavorite: false,
    createdAt: "2026-02-18",
  },
  {
    id: "19",
    slug: "attraction-tickets",
    title: "บัตรเข้าชมสถานที่และโชว์",
    category: "ticket",
    subcategory: "บัตรเข้าชมสถานที่",
    destination: ["bangkok", "pattaya", "phuket"],
    image: img.krabi,
    description:
      "บัตรเข้าชมสวนน้ำ สวนสนุก การแสดง และสถานที่ยอดนิยมในราคาพิเศษ",
    rating: 4.4,
    reviewCount: 88,
    price: 650,
    priceUnit: "บาท / คน",
    duration: "1day",
    travelType: ["family", "couple", "group"],
    features: ["รวมตั๋วเข้าชม"],
    badges: ["ยอดนิยม"],
    isFeatured: false,
    isFavorite: false,
    createdAt: "2025-10-05",
  },
  {
    id: "20",
    slug: "island-hopping",
    title: "ทัวร์เกาะและล่องเรือ",
    category: "activity",
    subcategory: "ทัวร์เกาะ",
    destination: ["phuket", "krabi", "samui", "surat"],
    image: img.phuket,
    description:
      "ทัวร์เกาะครบวงจร พร้อมเรือ สนอร์เกิล อาหารกลางวัน และประกันการเดินทาง",
    rating: 4.8,
    reviewCount: 276,
    price: 2500,
    priceUnit: "บาท / คน",
    duration: "1day",
    travelType: ["family", "couple", "group"],
    features: ["รวมอาหาร", "รวมตั๋วเข้าชม"],
    badges: ["ยอดนิยม"],
    isFeatured: false,
    isFavorite: false,
    createdAt: "2026-03-05",
  },
  {
    id: "21",
    slug: "spa-wellness",
    title: "สปาและ Wellness Experience",
    category: "activity",
    subcategory: "สปาและ Wellness",
    destination: ["bangkok", "huahin", "phuket"],
    image: img.samui,
    description:
      "แพ็กเกจสปาและเวลเนสรีทรีตสำหรับผ่อนคลายหลังการเดินทาง",
    rating: 4.7,
    reviewCount: 49,
    price: 3200,
    priceUnit: "บาท / คน",
    duration: "halfday",
    travelType: ["couple", "vip", "private"],
    features: [],
    badges: [],
    isFeatured: false,
    isFavorite: false,
    createdAt: "2025-12-19",
  },
  {
    id: "22",
    slug: "multilingual-guide",
    title: "มัคคุเทศก์หลายภาษา",
    category: "extra",
    subcategory: "มัคคุเทศก์หลายภาษา",
    destination: ["bangkok", "phuket", "chiangmai", "pattaya"],
    image: img.songkhla,
    description:
      "ไกด์มืออาชีพ ภาษาไทย อังกฤษ จีน ญี่ปุ่น และภาษาอื่นตามคำขอ",
    rating: 4.9,
    reviewCount: 133,
    price: 3500,
    priceUnit: "บาท / วัน",
    duration: "1day",
    travelType: ["private", "group", "corporate", "vip"],
    features: ["พร้อมไกด์"],
    badges: ["แนะนำ"],
    isFeatured: false,
    isFavorite: false,
    createdAt: "2026-01-28",
  },
  {
    id: "23",
    slug: "visa-support",
    title: "บริการ Visa Support",
    category: "extra",
    subcategory: "บริการ Visa Support",
    destination: ["bangkok", "international"],
    image: img.trang,
    description:
      "ให้คำปรึกษาและประสานงานเอกสารวีซ่าสำหรับทัวร์ต่างประเทศ",
    rating: 4.6,
    reviewCount: 57,
    price: 2500,
    priceUnit: "บาท / คน",
    duration: "custom",
    travelType: ["private", "family", "group"],
    features: ["ปรับแต่งโปรแกรมได้"],
    badges: [],
    isFeatured: false,
    isFavorite: false,
    createdAt: "2025-08-28",
  },
  {
    id: "24",
    slug: "vip-meet-greet",
    title: "บริการรับรองแขก VIP & Airport Representative",
    category: "extra",
    subcategory: "บริการรับรองแขก VIP",
    destination: ["bangkok", "phuket", "chiangmai"],
    image: img.krabi,
    description:
      "ทีมต้อนรับสนามบิน พาขึ้นรถและดูแลแขกสำคัญตลอดเส้นทาง",
    rating: 5.0,
    reviewCount: 34,
    price: 5500,
    priceUnit: "บาท / เที่ยว",
    duration: "halfday",
    travelType: ["vip", "corporate", "private"],
    features: ["พร้อมคนขับ"],
    badges: ["แนะนำ"],
    isFeatured: false,
    isFavorite: false,
    createdAt: "2026-02-08",
  },
];
